=begin
#API Nuvem Fiscal

#API para automação comercial e documentos fiscais.

The version of the OpenAPI document: 2.60.0

Generated by: https://openapi-generator.tech
Generator version: 7.14.0

=end

require 'date'
require 'time'

module NuvemFiscalClient
  # Grupo de Tributação da CBS.
  class CteSefazGCBS
    # Aliquota da CBS.
    attr_accessor :p_cbs

    attr_accessor :g_dif

    attr_accessor :g_dev_trib

    attr_accessor :g_red

    # Valor da CBS.
    attr_accessor :v_cbs

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'p_cbs' => :'pCBS',
        :'g_dif' => :'gDif',
        :'g_dev_trib' => :'gDevTrib',
        :'g_red' => :'gRed',
        :'v_cbs' => :'vCBS'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'p_cbs' => :'Float',
        :'g_dif' => :'CteSefazDif',
        :'g_dev_trib' => :'CteSefazDevTrib',
        :'g_red' => :'CteSefazRed',
        :'v_cbs' => :'Float'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
        :'p_cbs',
        :'v_cbs'
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `NuvemFiscalClient::CteSefazGCBS` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `NuvemFiscalClient::CteSefazGCBS`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'p_cbs')
        self.p_cbs = attributes[:'p_cbs']
      else
        self.p_cbs = nil
      end

      if attributes.key?(:'g_dif')
        self.g_dif = attributes[:'g_dif']
      end

      if attributes.key?(:'g_dev_trib')
        self.g_dev_trib = attributes[:'g_dev_trib']
      end

      if attributes.key?(:'g_red')
        self.g_red = attributes[:'g_red']
      end

      if attributes.key?(:'v_cbs')
        self.v_cbs = attributes[:'v_cbs']
      else
        self.v_cbs = nil
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @p_cbs < 0
        invalid_properties.push('invalid value for "p_cbs", must be greater than or equal to 0.')
      end

      if @v_cbs < 0
        invalid_properties.push('invalid value for "v_cbs", must be greater than or equal to 0.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @p_cbs < 0
      return false if @v_cbs < 0
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] p_cbs Value to be assigned
    def p_cbs=(p_cbs)
      if !p_cbs.nil? && p_cbs < 0
        fail ArgumentError, 'invalid value for "p_cbs", must be greater than or equal to 0.'
      end

      @p_cbs = p_cbs
    end

    # Custom attribute writer method with validation
    # @param [Object] v_cbs Value to be assigned
    def v_cbs=(v_cbs)
      if !v_cbs.nil? && v_cbs < 0
        fail ArgumentError, 'invalid value for "v_cbs", must be greater than or equal to 0.'
      end

      @v_cbs = v_cbs
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          p_cbs == o.p_cbs &&
          g_dif == o.g_dif &&
          g_dev_trib == o.g_dev_trib &&
          g_red == o.g_red &&
          v_cbs == o.v_cbs
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [p_cbs, g_dif, g_dev_trib, g_red, v_cbs].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def self._deserialize(type, value)
      case type.to_sym
      when :Time
        Time.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        # models (e.g. Pet) or oneOf
        klass = NuvemFiscalClient.const_get(type)
        klass.respond_to?(:openapi_any_of) || klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
