=begin
#API Nuvem Fiscal

#API para automação comercial e documentos fiscais.

The version of the OpenAPI document: 2.70.0

Generated by: https://openapi-generator.tech
Generator version: 7.14.0

=end

require 'date'
require 'time'

module NuvemFiscalClient
  # Grupo de informações do CT-e Normal e Substituto.
  class CteSefazInfCTeNorm
    attr_accessor :inf_carga

    attr_accessor :inf_doc

    attr_accessor :doc_ant

    attr_accessor :inf_modal

    attr_accessor :veic_novos

    attr_accessor :cobr

    attr_accessor :inf_cte_sub

    attr_accessor :inf_globalizado

    attr_accessor :inf_serv_vinc

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'inf_carga' => :'infCarga',
        :'inf_doc' => :'infDoc',
        :'doc_ant' => :'docAnt',
        :'inf_modal' => :'infModal',
        :'veic_novos' => :'veicNovos',
        :'cobr' => :'cobr',
        :'inf_cte_sub' => :'infCteSub',
        :'inf_globalizado' => :'infGlobalizado',
        :'inf_serv_vinc' => :'infServVinc'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'inf_carga' => :'CteSefazInfCarga',
        :'inf_doc' => :'CteSefazInfDoc',
        :'doc_ant' => :'CteSefazDocAnt',
        :'inf_modal' => :'CteSefazInfModal',
        :'veic_novos' => :'Array<CteSefazVeicNovos>',
        :'cobr' => :'CteSefazCobr',
        :'inf_cte_sub' => :'CteSefazInfCteSub',
        :'inf_globalizado' => :'CteSefazInfGlobalizado',
        :'inf_serv_vinc' => :'CteSefazInfServVinc'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `NuvemFiscalClient::CteSefazInfCTeNorm` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `NuvemFiscalClient::CteSefazInfCTeNorm`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'inf_carga')
        self.inf_carga = attributes[:'inf_carga']
      else
        self.inf_carga = nil
      end

      if attributes.key?(:'inf_doc')
        self.inf_doc = attributes[:'inf_doc']
      end

      if attributes.key?(:'doc_ant')
        self.doc_ant = attributes[:'doc_ant']
      end

      if attributes.key?(:'inf_modal')
        self.inf_modal = attributes[:'inf_modal']
      else
        self.inf_modal = nil
      end

      if attributes.key?(:'veic_novos')
        if (value = attributes[:'veic_novos']).is_a?(Array)
          self.veic_novos = value
        end
      end

      if attributes.key?(:'cobr')
        self.cobr = attributes[:'cobr']
      end

      if attributes.key?(:'inf_cte_sub')
        self.inf_cte_sub = attributes[:'inf_cte_sub']
      end

      if attributes.key?(:'inf_globalizado')
        self.inf_globalizado = attributes[:'inf_globalizado']
      end

      if attributes.key?(:'inf_serv_vinc')
        self.inf_serv_vinc = attributes[:'inf_serv_vinc']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @inf_carga.nil?
        invalid_properties.push('invalid value for "inf_carga", inf_carga cannot be nil.')
      end

      if @inf_modal.nil?
        invalid_properties.push('invalid value for "inf_modal", inf_modal cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @inf_carga.nil?
      return false if @inf_modal.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] inf_carga Value to be assigned
    def inf_carga=(inf_carga)
      if inf_carga.nil?
        fail ArgumentError, 'inf_carga cannot be nil'
      end

      @inf_carga = inf_carga
    end

    # Custom attribute writer method with validation
    # @param [Object] inf_modal Value to be assigned
    def inf_modal=(inf_modal)
      if inf_modal.nil?
        fail ArgumentError, 'inf_modal cannot be nil'
      end

      @inf_modal = inf_modal
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          inf_carga == o.inf_carga &&
          inf_doc == o.inf_doc &&
          doc_ant == o.doc_ant &&
          inf_modal == o.inf_modal &&
          veic_novos == o.veic_novos &&
          cobr == o.cobr &&
          inf_cte_sub == o.inf_cte_sub &&
          inf_globalizado == o.inf_globalizado &&
          inf_serv_vinc == o.inf_serv_vinc
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [inf_carga, inf_doc, doc_ant, inf_modal, veic_novos, cobr, inf_cte_sub, inf_globalizado, inf_serv_vinc].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def self._deserialize(type, value)
      case type.to_sym
      when :Time
        Time.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        # models (e.g. Pet) or oneOf
        klass = NuvemFiscalClient.const_get(type)
        klass.respond_to?(:openapi_any_of) || klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
