=begin
#API Nuvem Fiscal

#API para automação comercial e documentos fiscais.

The version of the OpenAPI document: 2.70.0

Generated by: https://openapi-generator.tech
Generator version: 7.14.0

=end

require 'date'
require 'time'

module NuvemFiscalClient
  # Informações do modal Aquaviário.
  class MdfeSefazAquav
    # Irin do navio sempre deverá ser informado.
    attr_accessor :irin

    # Código do tipo de embarcação.  Preencher com código da Tabela de Tipo de Embarcação definida no Ministério dos Transportes.
    attr_accessor :tp_emb

    # Código da embarcação.
    attr_accessor :c_embar

    # Nome da embarcação.
    attr_accessor :x_embar

    # Número da Viagem.
    attr_accessor :n_viag

    # Código do Porto de Embarque.  Preencher de acordo com Tabela de Portos definida no Ministério dos Transportes.
    attr_accessor :c_prt_emb

    # Código do Porto de Destino.  Preencher de acordo com Tabela de Portos definida no Ministério dos Transportes.
    attr_accessor :c_prt_dest

    # Porto de Transbordo.
    attr_accessor :prt_trans

    # Tipo de Navegação.  Preencher com:  * 0 - Interior  * 1 - Cabotagem
    attr_accessor :tp_nav

    attr_accessor :inf_term_carreg

    attr_accessor :inf_term_descarreg

    attr_accessor :inf_emb_comb

    attr_accessor :inf_unid_carga_vazia

    attr_accessor :inf_unid_transp_vazia

    # Maritime Mobile Service Identify.  Preencher com o MMSI (Maritime Mobile Service Identify) fornecido pela ANATEL ou autoridade de telecomunicações de origem da embarcação.
    attr_accessor :mmsi

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'irin' => :'irin',
        :'tp_emb' => :'tpEmb',
        :'c_embar' => :'cEmbar',
        :'x_embar' => :'xEmbar',
        :'n_viag' => :'nViag',
        :'c_prt_emb' => :'cPrtEmb',
        :'c_prt_dest' => :'cPrtDest',
        :'prt_trans' => :'prtTrans',
        :'tp_nav' => :'tpNav',
        :'inf_term_carreg' => :'infTermCarreg',
        :'inf_term_descarreg' => :'infTermDescarreg',
        :'inf_emb_comb' => :'infEmbComb',
        :'inf_unid_carga_vazia' => :'infUnidCargaVazia',
        :'inf_unid_transp_vazia' => :'infUnidTranspVazia',
        :'mmsi' => :'MMSI'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'irin' => :'String',
        :'tp_emb' => :'String',
        :'c_embar' => :'String',
        :'x_embar' => :'String',
        :'n_viag' => :'String',
        :'c_prt_emb' => :'String',
        :'c_prt_dest' => :'String',
        :'prt_trans' => :'String',
        :'tp_nav' => :'Integer',
        :'inf_term_carreg' => :'Array<MdfeSefazInfTermCarreg>',
        :'inf_term_descarreg' => :'Array<MdfeSefazInfTermDescarreg>',
        :'inf_emb_comb' => :'Array<MdfeSefazInfEmbComb>',
        :'inf_unid_carga_vazia' => :'Array<MdfeSefazInfUnidCargaVazia>',
        :'inf_unid_transp_vazia' => :'Array<MdfeSefazInfUnidTranspVazia>',
        :'mmsi' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
        :'irin',
        :'tp_emb',
        :'c_embar',
        :'x_embar',
        :'n_viag',
        :'c_prt_emb',
        :'c_prt_dest',
        :'prt_trans',
        :'tp_nav',
        :'mmsi'
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `NuvemFiscalClient::MdfeSefazAquav` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `NuvemFiscalClient::MdfeSefazAquav`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'irin')
        self.irin = attributes[:'irin']
      else
        self.irin = nil
      end

      if attributes.key?(:'tp_emb')
        self.tp_emb = attributes[:'tp_emb']
      else
        self.tp_emb = nil
      end

      if attributes.key?(:'c_embar')
        self.c_embar = attributes[:'c_embar']
      else
        self.c_embar = nil
      end

      if attributes.key?(:'x_embar')
        self.x_embar = attributes[:'x_embar']
      else
        self.x_embar = nil
      end

      if attributes.key?(:'n_viag')
        self.n_viag = attributes[:'n_viag']
      else
        self.n_viag = nil
      end

      if attributes.key?(:'c_prt_emb')
        self.c_prt_emb = attributes[:'c_prt_emb']
      else
        self.c_prt_emb = nil
      end

      if attributes.key?(:'c_prt_dest')
        self.c_prt_dest = attributes[:'c_prt_dest']
      else
        self.c_prt_dest = nil
      end

      if attributes.key?(:'prt_trans')
        self.prt_trans = attributes[:'prt_trans']
      end

      if attributes.key?(:'tp_nav')
        self.tp_nav = attributes[:'tp_nav']
      end

      if attributes.key?(:'inf_term_carreg')
        if (value = attributes[:'inf_term_carreg']).is_a?(Array)
          self.inf_term_carreg = value
        end
      end

      if attributes.key?(:'inf_term_descarreg')
        if (value = attributes[:'inf_term_descarreg']).is_a?(Array)
          self.inf_term_descarreg = value
        end
      end

      if attributes.key?(:'inf_emb_comb')
        if (value = attributes[:'inf_emb_comb']).is_a?(Array)
          self.inf_emb_comb = value
        end
      end

      if attributes.key?(:'inf_unid_carga_vazia')
        if (value = attributes[:'inf_unid_carga_vazia']).is_a?(Array)
          self.inf_unid_carga_vazia = value
        end
      end

      if attributes.key?(:'inf_unid_transp_vazia')
        if (value = attributes[:'inf_unid_transp_vazia']).is_a?(Array)
          self.inf_unid_transp_vazia = value
        end
      end

      if attributes.key?(:'mmsi')
        self.mmsi = attributes[:'mmsi']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @irin.to_s.length > 10
        invalid_properties.push('invalid value for "irin", the character length must be smaller than or equal to 10.')
      end

      if @irin.to_s.length < 1
        invalid_properties.push('invalid value for "irin", the character length must be greater than or equal to 1.')
      end

      if @c_embar.to_s.length > 10
        invalid_properties.push('invalid value for "c_embar", the character length must be smaller than or equal to 10.')
      end

      if @c_embar.to_s.length < 1
        invalid_properties.push('invalid value for "c_embar", the character length must be greater than or equal to 1.')
      end

      if @x_embar.to_s.length > 60
        invalid_properties.push('invalid value for "x_embar", the character length must be smaller than or equal to 60.')
      end

      if @x_embar.to_s.length < 1
        invalid_properties.push('invalid value for "x_embar", the character length must be greater than or equal to 1.')
      end

      if @c_prt_emb.to_s.length > 5
        invalid_properties.push('invalid value for "c_prt_emb", the character length must be smaller than or equal to 5.')
      end

      if @c_prt_emb.to_s.length < 1
        invalid_properties.push('invalid value for "c_prt_emb", the character length must be greater than or equal to 1.')
      end

      if @c_prt_dest.to_s.length > 5
        invalid_properties.push('invalid value for "c_prt_dest", the character length must be smaller than or equal to 5.')
      end

      if @c_prt_dest.to_s.length < 1
        invalid_properties.push('invalid value for "c_prt_dest", the character length must be greater than or equal to 1.')
      end

      if !@prt_trans.nil? && @prt_trans.to_s.length > 60
        invalid_properties.push('invalid value for "prt_trans", the character length must be smaller than or equal to 60.')
      end

      if !@prt_trans.nil? && @prt_trans.to_s.length < 1
        invalid_properties.push('invalid value for "prt_trans", the character length must be greater than or equal to 1.')
      end

      if !@inf_term_carreg.nil? && @inf_term_carreg.length > 5
        invalid_properties.push('invalid value for "inf_term_carreg", number of items must be less than or equal to 5.')
      end

      if !@inf_term_descarreg.nil? && @inf_term_descarreg.length > 5
        invalid_properties.push('invalid value for "inf_term_descarreg", number of items must be less than or equal to 5.')
      end

      if !@inf_emb_comb.nil? && @inf_emb_comb.length > 30
        invalid_properties.push('invalid value for "inf_emb_comb", number of items must be less than or equal to 30.')
      end

      if !@mmsi.nil? && @mmsi.to_s.length > 9
        invalid_properties.push('invalid value for "mmsi", the character length must be smaller than or equal to 9.')
      end

      if !@mmsi.nil? && @mmsi.to_s.length < 1
        invalid_properties.push('invalid value for "mmsi", the character length must be greater than or equal to 1.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @irin.to_s.length > 10
      return false if @irin.to_s.length < 1
      return false if @c_embar.to_s.length > 10
      return false if @c_embar.to_s.length < 1
      return false if @x_embar.to_s.length > 60
      return false if @x_embar.to_s.length < 1
      return false if @c_prt_emb.to_s.length > 5
      return false if @c_prt_emb.to_s.length < 1
      return false if @c_prt_dest.to_s.length > 5
      return false if @c_prt_dest.to_s.length < 1
      return false if !@prt_trans.nil? && @prt_trans.to_s.length > 60
      return false if !@prt_trans.nil? && @prt_trans.to_s.length < 1
      return false if !@inf_term_carreg.nil? && @inf_term_carreg.length > 5
      return false if !@inf_term_descarreg.nil? && @inf_term_descarreg.length > 5
      return false if !@inf_emb_comb.nil? && @inf_emb_comb.length > 30
      return false if !@mmsi.nil? && @mmsi.to_s.length > 9
      return false if !@mmsi.nil? && @mmsi.to_s.length < 1
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] irin Value to be assigned
    def irin=(irin)
      if !irin.nil? && irin.to_s.length > 10
        fail ArgumentError, 'invalid value for "irin", the character length must be smaller than or equal to 10.'
      end

      if !irin.nil? && irin.to_s.length < 1
        fail ArgumentError, 'invalid value for "irin", the character length must be greater than or equal to 1.'
      end

      @irin = irin
    end

    # Custom attribute writer method with validation
    # @param [Object] c_embar Value to be assigned
    def c_embar=(c_embar)
      if !c_embar.nil? && c_embar.to_s.length > 10
        fail ArgumentError, 'invalid value for "c_embar", the character length must be smaller than or equal to 10.'
      end

      if !c_embar.nil? && c_embar.to_s.length < 1
        fail ArgumentError, 'invalid value for "c_embar", the character length must be greater than or equal to 1.'
      end

      @c_embar = c_embar
    end

    # Custom attribute writer method with validation
    # @param [Object] x_embar Value to be assigned
    def x_embar=(x_embar)
      if !x_embar.nil? && x_embar.to_s.length > 60
        fail ArgumentError, 'invalid value for "x_embar", the character length must be smaller than or equal to 60.'
      end

      if !x_embar.nil? && x_embar.to_s.length < 1
        fail ArgumentError, 'invalid value for "x_embar", the character length must be greater than or equal to 1.'
      end

      @x_embar = x_embar
    end

    # Custom attribute writer method with validation
    # @param [Object] c_prt_emb Value to be assigned
    def c_prt_emb=(c_prt_emb)
      if !c_prt_emb.nil? && c_prt_emb.to_s.length > 5
        fail ArgumentError, 'invalid value for "c_prt_emb", the character length must be smaller than or equal to 5.'
      end

      if !c_prt_emb.nil? && c_prt_emb.to_s.length < 1
        fail ArgumentError, 'invalid value for "c_prt_emb", the character length must be greater than or equal to 1.'
      end

      @c_prt_emb = c_prt_emb
    end

    # Custom attribute writer method with validation
    # @param [Object] c_prt_dest Value to be assigned
    def c_prt_dest=(c_prt_dest)
      if !c_prt_dest.nil? && c_prt_dest.to_s.length > 5
        fail ArgumentError, 'invalid value for "c_prt_dest", the character length must be smaller than or equal to 5.'
      end

      if !c_prt_dest.nil? && c_prt_dest.to_s.length < 1
        fail ArgumentError, 'invalid value for "c_prt_dest", the character length must be greater than or equal to 1.'
      end

      @c_prt_dest = c_prt_dest
    end

    # Custom attribute writer method with validation
    # @param [Object] prt_trans Value to be assigned
    def prt_trans=(prt_trans)
      if !prt_trans.nil? && prt_trans.to_s.length > 60
        fail ArgumentError, 'invalid value for "prt_trans", the character length must be smaller than or equal to 60.'
      end

      if !prt_trans.nil? && prt_trans.to_s.length < 1
        fail ArgumentError, 'invalid value for "prt_trans", the character length must be greater than or equal to 1.'
      end

      @prt_trans = prt_trans
    end

    # Custom attribute writer method with validation
    # @param [Object] inf_term_carreg Value to be assigned
    def inf_term_carreg=(inf_term_carreg)
      if inf_term_carreg.nil?
        fail ArgumentError, 'inf_term_carreg cannot be nil'
      end

      if inf_term_carreg.length > 5
        fail ArgumentError, 'invalid value for "inf_term_carreg", number of items must be less than or equal to 5.'
      end

      @inf_term_carreg = inf_term_carreg
    end

    # Custom attribute writer method with validation
    # @param [Object] inf_term_descarreg Value to be assigned
    def inf_term_descarreg=(inf_term_descarreg)
      if inf_term_descarreg.nil?
        fail ArgumentError, 'inf_term_descarreg cannot be nil'
      end

      if inf_term_descarreg.length > 5
        fail ArgumentError, 'invalid value for "inf_term_descarreg", number of items must be less than or equal to 5.'
      end

      @inf_term_descarreg = inf_term_descarreg
    end

    # Custom attribute writer method with validation
    # @param [Object] inf_emb_comb Value to be assigned
    def inf_emb_comb=(inf_emb_comb)
      if inf_emb_comb.nil?
        fail ArgumentError, 'inf_emb_comb cannot be nil'
      end

      if inf_emb_comb.length > 30
        fail ArgumentError, 'invalid value for "inf_emb_comb", number of items must be less than or equal to 30.'
      end

      @inf_emb_comb = inf_emb_comb
    end

    # Custom attribute writer method with validation
    # @param [Object] mmsi Value to be assigned
    def mmsi=(mmsi)
      if !mmsi.nil? && mmsi.to_s.length > 9
        fail ArgumentError, 'invalid value for "mmsi", the character length must be smaller than or equal to 9.'
      end

      if !mmsi.nil? && mmsi.to_s.length < 1
        fail ArgumentError, 'invalid value for "mmsi", the character length must be greater than or equal to 1.'
      end

      @mmsi = mmsi
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          irin == o.irin &&
          tp_emb == o.tp_emb &&
          c_embar == o.c_embar &&
          x_embar == o.x_embar &&
          n_viag == o.n_viag &&
          c_prt_emb == o.c_prt_emb &&
          c_prt_dest == o.c_prt_dest &&
          prt_trans == o.prt_trans &&
          tp_nav == o.tp_nav &&
          inf_term_carreg == o.inf_term_carreg &&
          inf_term_descarreg == o.inf_term_descarreg &&
          inf_emb_comb == o.inf_emb_comb &&
          inf_unid_carga_vazia == o.inf_unid_carga_vazia &&
          inf_unid_transp_vazia == o.inf_unid_transp_vazia &&
          mmsi == o.mmsi
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [irin, tp_emb, c_embar, x_embar, n_viag, c_prt_emb, c_prt_dest, prt_trans, tp_nav, inf_term_carreg, inf_term_descarreg, inf_emb_comb, inf_unid_carga_vazia, inf_unid_transp_vazia, mmsi].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def self._deserialize(type, value)
      case type.to_sym
      when :Time
        Time.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        # models (e.g. Pet) or oneOf
        klass = NuvemFiscalClient.const_get(type)
        klass.respond_to?(:openapi_any_of) || klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
