=begin
#API Nuvem Fiscal

#API para automação comercial e documentos fiscais.

The version of the OpenAPI document: 2.70.0

Generated by: https://openapi-generator.tech
Generator version: 7.14.0

=end

require 'date'
require 'time'

module NuvemFiscalClient
  # Informações do ICMS de partilha com a UF destinatária.
  class NfcomSefazICMSUFDest
    attr_accessor :c_uf_dest

    # Valor da BC do ICMS na UF de destino.
    attr_accessor :v_bcuf_dest

    # Percentual do ICMS relativo ao Fundo de Combate à pobreza (FCP) na UF de destino.  Alíquota adotada nas operações internas na UF do destinatário.
    attr_accessor :p_fcpuf_dest

    # Alíquota interna da UF de destino.  Alíquota adotada nas operações internas na UF do destinatário.
    attr_accessor :p_icmsuf_dest

    # Valor do ICMS relativo ao Fundo de Combate á Pobreza (FCP) da UF de destino.
    attr_accessor :v_fcpuf_dest

    # Valor do ICMS de partilha para a UF de destino.
    attr_accessor :v_icmsuf_dest

    # Valor do ICMS de partilha para a UF de emissão.
    attr_accessor :v_icmsuf_emi

    # Código de Benefício Fiscal na UF destino aplicado ao item.  Código de Benefício Fiscal utilizado pela UF, aplicado ao  item.
    attr_accessor :c_benef_uf_dest

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'c_uf_dest' => :'cUFDest',
        :'v_bcuf_dest' => :'vBCUFDest',
        :'p_fcpuf_dest' => :'pFCPUFDest',
        :'p_icmsuf_dest' => :'pICMSUFDest',
        :'v_fcpuf_dest' => :'vFCPUFDest',
        :'v_icmsuf_dest' => :'vICMSUFDest',
        :'v_icmsuf_emi' => :'vICMSUFEmi',
        :'c_benef_uf_dest' => :'cBenefUFDest'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'c_uf_dest' => :'Integer',
        :'v_bcuf_dest' => :'Float',
        :'p_fcpuf_dest' => :'Float',
        :'p_icmsuf_dest' => :'Float',
        :'v_fcpuf_dest' => :'Float',
        :'v_icmsuf_dest' => :'Float',
        :'v_icmsuf_emi' => :'Float',
        :'c_benef_uf_dest' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
        :'c_uf_dest',
        :'v_bcuf_dest',
        :'p_fcpuf_dest',
        :'p_icmsuf_dest',
        :'v_fcpuf_dest',
        :'v_icmsuf_dest',
        :'v_icmsuf_emi',
        :'c_benef_uf_dest'
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `NuvemFiscalClient::NfcomSefazICMSUFDest` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `NuvemFiscalClient::NfcomSefazICMSUFDest`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'c_uf_dest')
        self.c_uf_dest = attributes[:'c_uf_dest']
      end

      if attributes.key?(:'v_bcuf_dest')
        self.v_bcuf_dest = attributes[:'v_bcuf_dest']
      else
        self.v_bcuf_dest = nil
      end

      if attributes.key?(:'p_fcpuf_dest')
        self.p_fcpuf_dest = attributes[:'p_fcpuf_dest']
      else
        self.p_fcpuf_dest = nil
      end

      if attributes.key?(:'p_icmsuf_dest')
        self.p_icmsuf_dest = attributes[:'p_icmsuf_dest']
      else
        self.p_icmsuf_dest = nil
      end

      if attributes.key?(:'v_fcpuf_dest')
        self.v_fcpuf_dest = attributes[:'v_fcpuf_dest']
      else
        self.v_fcpuf_dest = nil
      end

      if attributes.key?(:'v_icmsuf_dest')
        self.v_icmsuf_dest = attributes[:'v_icmsuf_dest']
      else
        self.v_icmsuf_dest = nil
      end

      if attributes.key?(:'v_icmsuf_emi')
        self.v_icmsuf_emi = attributes[:'v_icmsuf_emi']
      else
        self.v_icmsuf_emi = nil
      end

      if attributes.key?(:'c_benef_uf_dest')
        self.c_benef_uf_dest = attributes[:'c_benef_uf_dest']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @v_bcuf_dest < 0
        invalid_properties.push('invalid value for "v_bcuf_dest", must be greater than or equal to 0.')
      end

      if @p_fcpuf_dest < 0
        invalid_properties.push('invalid value for "p_fcpuf_dest", must be greater than or equal to 0.')
      end

      if @p_icmsuf_dest < 0
        invalid_properties.push('invalid value for "p_icmsuf_dest", must be greater than or equal to 0.')
      end

      if @v_fcpuf_dest < 0
        invalid_properties.push('invalid value for "v_fcpuf_dest", must be greater than or equal to 0.')
      end

      if @v_icmsuf_dest < 0
        invalid_properties.push('invalid value for "v_icmsuf_dest", must be greater than or equal to 0.')
      end

      if @v_icmsuf_emi < 0
        invalid_properties.push('invalid value for "v_icmsuf_emi", must be greater than or equal to 0.')
      end

      if !@c_benef_uf_dest.nil? && @c_benef_uf_dest.to_s.length > 10
        invalid_properties.push('invalid value for "c_benef_uf_dest", the character length must be smaller than or equal to 10.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @v_bcuf_dest < 0
      return false if @p_fcpuf_dest < 0
      return false if @p_icmsuf_dest < 0
      return false if @v_fcpuf_dest < 0
      return false if @v_icmsuf_dest < 0
      return false if @v_icmsuf_emi < 0
      return false if !@c_benef_uf_dest.nil? && @c_benef_uf_dest.to_s.length > 10
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] v_bcuf_dest Value to be assigned
    def v_bcuf_dest=(v_bcuf_dest)
      if !v_bcuf_dest.nil? && v_bcuf_dest < 0
        fail ArgumentError, 'invalid value for "v_bcuf_dest", must be greater than or equal to 0.'
      end

      @v_bcuf_dest = v_bcuf_dest
    end

    # Custom attribute writer method with validation
    # @param [Object] p_fcpuf_dest Value to be assigned
    def p_fcpuf_dest=(p_fcpuf_dest)
      if !p_fcpuf_dest.nil? && p_fcpuf_dest < 0
        fail ArgumentError, 'invalid value for "p_fcpuf_dest", must be greater than or equal to 0.'
      end

      @p_fcpuf_dest = p_fcpuf_dest
    end

    # Custom attribute writer method with validation
    # @param [Object] p_icmsuf_dest Value to be assigned
    def p_icmsuf_dest=(p_icmsuf_dest)
      if !p_icmsuf_dest.nil? && p_icmsuf_dest < 0
        fail ArgumentError, 'invalid value for "p_icmsuf_dest", must be greater than or equal to 0.'
      end

      @p_icmsuf_dest = p_icmsuf_dest
    end

    # Custom attribute writer method with validation
    # @param [Object] v_fcpuf_dest Value to be assigned
    def v_fcpuf_dest=(v_fcpuf_dest)
      if !v_fcpuf_dest.nil? && v_fcpuf_dest < 0
        fail ArgumentError, 'invalid value for "v_fcpuf_dest", must be greater than or equal to 0.'
      end

      @v_fcpuf_dest = v_fcpuf_dest
    end

    # Custom attribute writer method with validation
    # @param [Object] v_icmsuf_dest Value to be assigned
    def v_icmsuf_dest=(v_icmsuf_dest)
      if !v_icmsuf_dest.nil? && v_icmsuf_dest < 0
        fail ArgumentError, 'invalid value for "v_icmsuf_dest", must be greater than or equal to 0.'
      end

      @v_icmsuf_dest = v_icmsuf_dest
    end

    # Custom attribute writer method with validation
    # @param [Object] v_icmsuf_emi Value to be assigned
    def v_icmsuf_emi=(v_icmsuf_emi)
      if !v_icmsuf_emi.nil? && v_icmsuf_emi < 0
        fail ArgumentError, 'invalid value for "v_icmsuf_emi", must be greater than or equal to 0.'
      end

      @v_icmsuf_emi = v_icmsuf_emi
    end

    # Custom attribute writer method with validation
    # @param [Object] c_benef_uf_dest Value to be assigned
    def c_benef_uf_dest=(c_benef_uf_dest)
      if !c_benef_uf_dest.nil? && c_benef_uf_dest.to_s.length > 10
        fail ArgumentError, 'invalid value for "c_benef_uf_dest", the character length must be smaller than or equal to 10.'
      end

      @c_benef_uf_dest = c_benef_uf_dest
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          c_uf_dest == o.c_uf_dest &&
          v_bcuf_dest == o.v_bcuf_dest &&
          p_fcpuf_dest == o.p_fcpuf_dest &&
          p_icmsuf_dest == o.p_icmsuf_dest &&
          v_fcpuf_dest == o.v_fcpuf_dest &&
          v_icmsuf_dest == o.v_icmsuf_dest &&
          v_icmsuf_emi == o.v_icmsuf_emi &&
          c_benef_uf_dest == o.c_benef_uf_dest
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [c_uf_dest, v_bcuf_dest, p_fcpuf_dest, p_icmsuf_dest, v_fcpuf_dest, v_icmsuf_dest, v_icmsuf_emi, c_benef_uf_dest].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def self._deserialize(type, value)
      case type.to_sym
      when :Time
        Time.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        # models (e.g. Pet) or oneOf
        klass = NuvemFiscalClient.const_get(type)
        klass.respond_to?(:openapi_any_of) || klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
