=begin
#API Nuvem Fiscal

#API para automação comercial e documentos fiscais.

The version of the OpenAPI document: 2.60.0

Generated by: https://openapi-generator.tech
Generator version: 7.14.0

=end

require 'date'
require 'time'

module NuvemFiscalClient
  # Identificação da NFCom.
  class NfcomSefazIde
    # Código da UF de emissão e autorização da NFCom.  Código da UF de emissão e autorização do Documento Fiscal. Utilizar a  Tabela do IBGE de código de unidades da federação.
    attr_accessor :c_uf

    # Tipo do Ambiente:  * 1 - Produção  * 2 - Homologação
    attr_accessor :tp_amb

    # Modelo da NFCom.  Utilizar o código 62 para identificação da NFCom.
    attr_accessor :mod

    # Série do documento fiscal.  Informar a série do documento fiscal (informar zero para série única).
    attr_accessor :serie

    # Número do documento fiscal.  Número que identifica o documento fiscal 1 a 999999999.
    attr_accessor :n_nf

    # Código numérico que compõe a Chave de Acesso.  Código aleatório gerado pelo emitente, com o objetivo de evitar acessos indevidos ao documento.    *Geramos automaticamente quando nenhum valor é informado.*
    attr_accessor :c_nf

    # Digito verificador da chave de acesso.  Informar o dígito  de controle da chave de acesso documento fiscal, que deve ser calculado com a aplicação do algoritmo módulo 11 (base 2,9) da chave de acesso.    *Geramos automaticamente quando nenhum valor é informado.*
    attr_accessor :c_dv

    # Data e hora de emissão do documento fiscal.  Formato AAAA-MM-DDTHH:MM:DD TZD.
    attr_accessor :dh_emi

    # Forma de emissão do Documento Fiscal.  * 1 - Normal  * 2 - Contingência
    attr_accessor :tp_emis

    # Identificação do número do Site do Autorizador de recepção da NFCom.  Se o autorizador da NFCom possuir apenas um site deverá ser informado com Zero (0), em caso de Autorizador trabalhar com múltiplos sites indicar o número do site para qual foi endereçada a NFCOM (1 a 9).  Observação: o ambiente autorizador que trabalhar com mais de um Site deverá divulgar para cada endereço de site qual número correspondente de nSiteAutoriz o contribuinte pode usar.
    attr_accessor :n_site_autoriz

    # Código do município de ocorrência do fato gerador.
    attr_accessor :c_mun_fg

    # Finalidade de emissão da NFCom.  * 0 - NFCom Normal  * 3 - NFCom de Substituição  * 4 - NFCom de Ajuste
    attr_accessor :fin_nf_com

    # Tipo de Faturamento da NFCom.  * 0 - Faturamento Normal  * 1 - Faturamento centralizado  * 2 - Cofaturamento
    attr_accessor :tp_fat

    # Versão do processo de emissão.  Informar a versão do aplicativo emissor de NFCom.
    attr_accessor :ver_proc

    # Indicador de serviço pré-pago.  * 1 - Serviço pré-pago (informar a tag somente se a nota for referente a um serviço exclusivamente pré-pago)
    attr_accessor :ind_pre_pago

    # Indicador de Sessão de Meios de Rede.  Uma vez informado (valor = 1), essa tag dispensa geração do grupo Fatura.  Apenas para notas dos tipos Normal e Substituição com tipo de faturamento normal.
    attr_accessor :ind_cessao_meios_rede

    # Indicador de nota de entrada.  * 1 - Informar quando for nota de ajuste e possuir itens com CFOP de entrada
    attr_accessor :ind_nota_entrada

    # Data e Hora da entrada em contingência.  Informar a data e hora no formato AAAA-MM-DDTHH:MM:SS.
    attr_accessor :dh_cont

    # Justificativa da entrada em contingência.
    attr_accessor :x_just

    attr_accessor :g_compra_gov

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'c_uf' => :'cUF',
        :'tp_amb' => :'tpAmb',
        :'mod' => :'mod',
        :'serie' => :'serie',
        :'n_nf' => :'nNF',
        :'c_nf' => :'cNF',
        :'c_dv' => :'cDV',
        :'dh_emi' => :'dhEmi',
        :'tp_emis' => :'tpEmis',
        :'n_site_autoriz' => :'nSiteAutoriz',
        :'c_mun_fg' => :'cMunFG',
        :'fin_nf_com' => :'finNFCom',
        :'tp_fat' => :'tpFat',
        :'ver_proc' => :'verProc',
        :'ind_pre_pago' => :'indPrePago',
        :'ind_cessao_meios_rede' => :'indCessaoMeiosRede',
        :'ind_nota_entrada' => :'indNotaEntrada',
        :'dh_cont' => :'dhCont',
        :'x_just' => :'xJust',
        :'g_compra_gov' => :'gCompraGov'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'c_uf' => :'Integer',
        :'tp_amb' => :'Integer',
        :'mod' => :'Integer',
        :'serie' => :'Integer',
        :'n_nf' => :'Integer',
        :'c_nf' => :'String',
        :'c_dv' => :'Integer',
        :'dh_emi' => :'Time',
        :'tp_emis' => :'Integer',
        :'n_site_autoriz' => :'Integer',
        :'c_mun_fg' => :'String',
        :'fin_nf_com' => :'Integer',
        :'tp_fat' => :'Integer',
        :'ver_proc' => :'String',
        :'ind_pre_pago' => :'Integer',
        :'ind_cessao_meios_rede' => :'Integer',
        :'ind_nota_entrada' => :'Integer',
        :'dh_cont' => :'Time',
        :'x_just' => :'String',
        :'g_compra_gov' => :'NfcomSefazCompraGovReduzido'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
        :'c_uf',
        :'tp_amb',
        :'mod',
        :'serie',
        :'n_nf',
        :'c_nf',
        :'c_dv',
        :'dh_emi',
        :'tp_emis',
        :'n_site_autoriz',
        :'c_mun_fg',
        :'fin_nf_com',
        :'tp_fat',
        :'ver_proc',
        :'ind_pre_pago',
        :'ind_cessao_meios_rede',
        :'ind_nota_entrada',
        :'dh_cont',
        :'x_just',
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `NuvemFiscalClient::NfcomSefazIde` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `NuvemFiscalClient::NfcomSefazIde`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'c_uf')
        self.c_uf = attributes[:'c_uf']
      else
        self.c_uf = nil
      end

      if attributes.key?(:'tp_amb')
        self.tp_amb = attributes[:'tp_amb']
      end

      if attributes.key?(:'mod')
        self.mod = attributes[:'mod']
      end

      if attributes.key?(:'serie')
        self.serie = attributes[:'serie']
      else
        self.serie = nil
      end

      if attributes.key?(:'n_nf')
        self.n_nf = attributes[:'n_nf']
      else
        self.n_nf = nil
      end

      if attributes.key?(:'c_nf')
        self.c_nf = attributes[:'c_nf']
      end

      if attributes.key?(:'c_dv')
        self.c_dv = attributes[:'c_dv']
      end

      if attributes.key?(:'dh_emi')
        self.dh_emi = attributes[:'dh_emi']
      else
        self.dh_emi = nil
      end

      if attributes.key?(:'tp_emis')
        self.tp_emis = attributes[:'tp_emis']
      else
        self.tp_emis = nil
      end

      if attributes.key?(:'n_site_autoriz')
        self.n_site_autoriz = attributes[:'n_site_autoriz']
      else
        self.n_site_autoriz = nil
      end

      if attributes.key?(:'c_mun_fg')
        self.c_mun_fg = attributes[:'c_mun_fg']
      else
        self.c_mun_fg = nil
      end

      if attributes.key?(:'fin_nf_com')
        self.fin_nf_com = attributes[:'fin_nf_com']
      else
        self.fin_nf_com = nil
      end

      if attributes.key?(:'tp_fat')
        self.tp_fat = attributes[:'tp_fat']
      else
        self.tp_fat = nil
      end

      if attributes.key?(:'ver_proc')
        self.ver_proc = attributes[:'ver_proc']
      else
        self.ver_proc = nil
      end

      if attributes.key?(:'ind_pre_pago')
        self.ind_pre_pago = attributes[:'ind_pre_pago']
      end

      if attributes.key?(:'ind_cessao_meios_rede')
        self.ind_cessao_meios_rede = attributes[:'ind_cessao_meios_rede']
      end

      if attributes.key?(:'ind_nota_entrada')
        self.ind_nota_entrada = attributes[:'ind_nota_entrada']
      end

      if attributes.key?(:'dh_cont')
        self.dh_cont = attributes[:'dh_cont']
      end

      if attributes.key?(:'x_just')
        self.x_just = attributes[:'x_just']
      end

      if attributes.key?(:'g_compra_gov')
        self.g_compra_gov = attributes[:'g_compra_gov']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @serie > 999
        invalid_properties.push('invalid value for "serie", must be smaller than or equal to 999.')
      end

      if @serie < 0
        invalid_properties.push('invalid value for "serie", must be greater than or equal to 0.')
      end

      if @n_nf > 999999999
        invalid_properties.push('invalid value for "n_nf", must be smaller than or equal to 999999999.')
      end

      if @n_nf < 1
        invalid_properties.push('invalid value for "n_nf", must be greater than or equal to 1.')
      end

      if !@c_dv.nil? && @c_dv > 9
        invalid_properties.push('invalid value for "c_dv", must be smaller than or equal to 9.')
      end

      if !@c_dv.nil? && @c_dv < 0
        invalid_properties.push('invalid value for "c_dv", must be greater than or equal to 0.')
      end

      if @n_site_autoriz > 9
        invalid_properties.push('invalid value for "n_site_autoriz", must be smaller than or equal to 9.')
      end

      if @n_site_autoriz < 0
        invalid_properties.push('invalid value for "n_site_autoriz", must be greater than or equal to 0.')
      end

      if @ver_proc.to_s.length > 20
        invalid_properties.push('invalid value for "ver_proc", the character length must be smaller than or equal to 20.')
      end

      if @ver_proc.to_s.length < 1
        invalid_properties.push('invalid value for "ver_proc", the character length must be greater than or equal to 1.')
      end

      if !@x_just.nil? && @x_just.to_s.length > 256
        invalid_properties.push('invalid value for "x_just", the character length must be smaller than or equal to 256.')
      end

      if !@x_just.nil? && @x_just.to_s.length < 15
        invalid_properties.push('invalid value for "x_just", the character length must be greater than or equal to 15.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @serie > 999
      return false if @serie < 0
      return false if @n_nf > 999999999
      return false if @n_nf < 1
      return false if !@c_dv.nil? && @c_dv > 9
      return false if !@c_dv.nil? && @c_dv < 0
      return false if @n_site_autoriz > 9
      return false if @n_site_autoriz < 0
      return false if @ver_proc.to_s.length > 20
      return false if @ver_proc.to_s.length < 1
      return false if !@x_just.nil? && @x_just.to_s.length > 256
      return false if !@x_just.nil? && @x_just.to_s.length < 15
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] serie Value to be assigned
    def serie=(serie)
      if !serie.nil? && serie > 999
        fail ArgumentError, 'invalid value for "serie", must be smaller than or equal to 999.'
      end

      if !serie.nil? && serie < 0
        fail ArgumentError, 'invalid value for "serie", must be greater than or equal to 0.'
      end

      @serie = serie
    end

    # Custom attribute writer method with validation
    # @param [Object] n_nf Value to be assigned
    def n_nf=(n_nf)
      if !n_nf.nil? && n_nf > 999999999
        fail ArgumentError, 'invalid value for "n_nf", must be smaller than or equal to 999999999.'
      end

      if !n_nf.nil? && n_nf < 1
        fail ArgumentError, 'invalid value for "n_nf", must be greater than or equal to 1.'
      end

      @n_nf = n_nf
    end

    # Custom attribute writer method with validation
    # @param [Object] c_dv Value to be assigned
    def c_dv=(c_dv)
      if !c_dv.nil? && c_dv > 9
        fail ArgumentError, 'invalid value for "c_dv", must be smaller than or equal to 9.'
      end

      if !c_dv.nil? && c_dv < 0
        fail ArgumentError, 'invalid value for "c_dv", must be greater than or equal to 0.'
      end

      @c_dv = c_dv
    end

    # Custom attribute writer method with validation
    # @param [Object] n_site_autoriz Value to be assigned
    def n_site_autoriz=(n_site_autoriz)
      if !n_site_autoriz.nil? && n_site_autoriz > 9
        fail ArgumentError, 'invalid value for "n_site_autoriz", must be smaller than or equal to 9.'
      end

      if !n_site_autoriz.nil? && n_site_autoriz < 0
        fail ArgumentError, 'invalid value for "n_site_autoriz", must be greater than or equal to 0.'
      end

      @n_site_autoriz = n_site_autoriz
    end

    # Custom attribute writer method with validation
    # @param [Object] ver_proc Value to be assigned
    def ver_proc=(ver_proc)
      if !ver_proc.nil? && ver_proc.to_s.length > 20
        fail ArgumentError, 'invalid value for "ver_proc", the character length must be smaller than or equal to 20.'
      end

      if !ver_proc.nil? && ver_proc.to_s.length < 1
        fail ArgumentError, 'invalid value for "ver_proc", the character length must be greater than or equal to 1.'
      end

      @ver_proc = ver_proc
    end

    # Custom attribute writer method with validation
    # @param [Object] x_just Value to be assigned
    def x_just=(x_just)
      if !x_just.nil? && x_just.to_s.length > 256
        fail ArgumentError, 'invalid value for "x_just", the character length must be smaller than or equal to 256.'
      end

      if !x_just.nil? && x_just.to_s.length < 15
        fail ArgumentError, 'invalid value for "x_just", the character length must be greater than or equal to 15.'
      end

      @x_just = x_just
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          c_uf == o.c_uf &&
          tp_amb == o.tp_amb &&
          mod == o.mod &&
          serie == o.serie &&
          n_nf == o.n_nf &&
          c_nf == o.c_nf &&
          c_dv == o.c_dv &&
          dh_emi == o.dh_emi &&
          tp_emis == o.tp_emis &&
          n_site_autoriz == o.n_site_autoriz &&
          c_mun_fg == o.c_mun_fg &&
          fin_nf_com == o.fin_nf_com &&
          tp_fat == o.tp_fat &&
          ver_proc == o.ver_proc &&
          ind_pre_pago == o.ind_pre_pago &&
          ind_cessao_meios_rede == o.ind_cessao_meios_rede &&
          ind_nota_entrada == o.ind_nota_entrada &&
          dh_cont == o.dh_cont &&
          x_just == o.x_just &&
          g_compra_gov == o.g_compra_gov
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [c_uf, tp_amb, mod, serie, n_nf, c_nf, c_dv, dh_emi, tp_emis, n_site_autoriz, c_mun_fg, fin_nf_com, tp_fat, ver_proc, ind_pre_pago, ind_cessao_meios_rede, ind_nota_entrada, dh_cont, x_just, g_compra_gov].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def self._deserialize(type, value)
      case type.to_sym
      when :Time
        Time.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        # models (e.g. Pet) or oneOf
        klass = NuvemFiscalClient.const_get(type)
        klass.respond_to?(:openapi_any_of) || klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
