=begin
#API Nuvem Fiscal

#API para automação comercial e documentos fiscais.

The version of the OpenAPI document: 2.60.0

Generated by: https://openapi-generator.tech
Generator version: 7.14.0

=end

require 'spec_helper'
require 'json'

# Unit tests for NuvemFiscalClient::CnpjApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'CnpjApi' do
  before do
    # run before each test
    @api_instance = NuvemFiscalClient::CnpjApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of CnpjApi' do
    it 'should create an instance of CnpjApi' do
      expect(@api_instance).to be_instance_of(NuvemFiscalClient::CnpjApi)
    end
  end

  # unit tests for consultar_cnpj
  # Consultar dados do CNPJ
  # **Informações adicionais**:  - Cota: &lt;a href&#x3D;\&quot;/docs/limites#cnpj-consultas\&quot;&gt;cnpj-consultas&lt;/a&gt;  - Consumo: 1 unidade por requisição.
  # @param cnpj CNPJ sem máscara.
  # @param [Hash] opts the optional parameters
  # @return [CnpjEmpresa]
  describe 'consultar_cnpj test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for listar_cnpj
  # Listar estabelecimentos ativos a partir da base de CNPJ
  # Retorna uma lista de estabelecimentos de acordo com os critérios de busca utilizados.  Somente serão retornados estabelecimentos com situação cadastral \&quot;Ativa\&quot;.    **Informações adicionais**:  - Cota: &lt;a href&#x3D;\&quot;/docs/limites#cnpj-listagem\&quot;&gt;cnpj-listagem&lt;/a&gt;  - Consumo: 1 unidade por estabelecimento listado ou requisição.
  # @param cnae_principal Filtro pelo código CNAE da atividade principal do estabelecimento.  Utilize o valor sem máscara.
  # @param municipio Filtro pelo código IBGE ou TOM (Tabela de Órgãos e Municípios) do município do estabelecimento.  Utilize o valor sem máscara.
  # @param natureza_juridica Filtro pela natureza jurídica do estabelecimento   Utilize o valor de quatro dígitos sem máscara.
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :top Limite no número de objetos a serem retornados pela API, entre 1 e 100.
  # @option opts [Integer] :skip Quantidade de objetos que serão ignorados antes da lista começar a ser retornada.
  # @option opts [Boolean] :inlinecount Inclui no JSON de resposta, na propriedade &#x60;@count&#x60;, o número total de registros que o filtro retornaria, independente dos filtros de paginação.
  # @return [CnpjListagem]
  describe 'listar_cnpj test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
