=begin
#API Nuvem Fiscal

#API para automação comercial e documentos fiscais.

The version of the OpenAPI document: 2.60.0

Generated by: https://openapi-generator.tech
Generator version: 7.14.0

=end

require 'spec_helper'
require 'json'

# Unit tests for NuvemFiscalClient::ContaApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'ContaApi' do
  before do
    # run before each test
    @api_instance = NuvemFiscalClient::ContaApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ContaApi' do
    it 'should create an instance of ContaApi' do
      expect(@api_instance).to be_instance_of(NuvemFiscalClient::ContaApi)
    end
  end

  # unit tests for consultar_cota_conta
  # Consultar o limite de uso e o consumo de uma cota específica.
  # @param nome Nome da cota a ser consultada.
  # @param [Hash] opts the optional parameters
  # @return [ContaCota]
  describe 'consultar_cota_conta test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for listar_cotas_conta
  # Consultar os limites de uso e consumo de todas as cotas existentes.
  # @param [Hash] opts the optional parameters
  # @return [ContaCotaListagem]
  describe 'listar_cotas_conta test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
