=begin
#API Nuvem Fiscal

#API para automação comercial e documentos fiscais.

The version of the OpenAPI document: 2.60.0

Generated by: https://openapi-generator.tech
Generator version: 7.14.0

=end

require 'spec_helper'
require 'json'

# Unit tests for NuvemFiscalClient::DceApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'DceApi' do
  before do
    # run before each test
    @api_instance = NuvemFiscalClient::DceApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of DceApi' do
    it 'should create an instance of DceApi' do
      expect(@api_instance).to be_instance_of(NuvemFiscalClient::DceApi)
    end
  end

  # unit tests for baixar_pdf_dce
  # Baixar PDF do DACE
  # @param id ID único da DC-e gerado pela Nuvem Fiscal.
  # @param [Hash] opts the optional parameters
  # @return [File]
  describe 'baixar_pdf_dce test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for baixar_xml_cancelamento_dce
  # Baixar XML do cancelamento
  # @param id ID único da DC-e gerada pela Nuvem Fiscal.
  # @param [Hash] opts the optional parameters
  # @return [File]
  describe 'baixar_xml_cancelamento_dce test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for baixar_xml_dce
  # Baixar XML da DC-e processada
  # Utilize esse endpoint para obter o XML da DC-e enviada para a SEFAZ, complementado com a informação do protocolo de autorização de uso (TAG raiz &#x60;dceProc&#x60;).    O XML só estará disponível nesse endpoint caso a DC-e tenha sido autorizada pela SEFAZ. Para obter o XML nos demais casos, utilize o endpoint &#x60;GET /dce/{id}/xml/declaracao&#x60;.
  # @param id ID único da DC-e gerada pela Nuvem Fiscal.
  # @param [Hash] opts the optional parameters
  # @return [File]
  describe 'baixar_xml_dce test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for baixar_xml_dce_declaracao
  # Baixar XML da DC-e
  # Utilize esse endpoint para obter o XML da DC-e enviada para a SEFAZ.    O XML estará disponível nesse endpoint mesmo em casos que a declaração tenha sido rejeitada.
  # @param id ID único da DC-e gerada pela Nuvem Fiscal.
  # @param [Hash] opts the optional parameters
  # @return [File]
  describe 'baixar_xml_dce_declaracao test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for baixar_xml_dce_protocolo
  # Baixar XML do Protocolo da SEFAZ
  # @param id ID único da DC-e gerada pela Nuvem Fiscal.
  # @param [Hash] opts the optional parameters
  # @return [File]
  describe 'baixar_xml_dce_protocolo test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for cancelar_dce
  # Cancelar uma DC-e autorizada
  # **Informações adicionais**:  - Cota: &lt;a href&#x3D;\&quot;/docs/limites#dfe-eventos\&quot;&gt;dfe-eventos&lt;/a&gt;  - Consumo: 1 unidade por requisição.
  # @param id ID único da DC-e gerada pela Nuvem Fiscal.
  # @param [Hash] opts the optional parameters
  # @option opts [DcePedidoCancelamento] :body 
  # @return [DfeCancelamento]
  describe 'cancelar_dce test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for consultar_cancelamento_dce
  # Consultar o cancelamento da DC-e
  # @param id ID único da DC-e gerada pela Nuvem Fiscal.
  # @param [Hash] opts the optional parameters
  # @return [DfeCancelamento]
  describe 'consultar_cancelamento_dce test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for consultar_dce
  # Consultar DC-e
  # Consulta os detalhes de uma DC-e já existente. Forneça o ID único obtido de uma requisição de emissão ou de listagem de DC-e e a Nuvem Fiscal irá retornar as informações da DC-e correspondente.
  # @param id ID único da DC-e gerada pela Nuvem Fiscal.
  # @param [Hash] opts the optional parameters
  # @return [Dfe]
  describe 'consultar_dce test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for consultar_status_sefaz_dce
  # Consulta do Status do Serviço na SEFAZ Autorizadora
  # Consulta do status do serviço prestado pelo Portal da Secretaria de Fazenda Estadual.    A Nuvem Fiscal mantém a última consulta em cache por 5 minutos, evitando sobrecarregar desnecessariamente os servidores da SEFAZ.
  # @param cpf_cnpj CPF/CNPJ do emitente.  Utilize o valor sem máscara.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :autorizador Ambiente Autorizador.    Autorizadores disponíveis: &#x60;AN&#x60;.    *Caso não seja informado, será utilizado o ambiente autorizador da UF do emitente.*
  # @return [DfeSefazStatus]
  describe 'consultar_status_sefaz_dce test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for emitir_dce
  # Emitir DC-e
  # **Informações adicionais**:  - Cota: &lt;a href&#x3D;\&quot;/docs/limites#dfe-eventos\&quot;&gt;dfe-eventos&lt;/a&gt;  - Consumo: 1 unidade por requisição.
  # @param body 
  # @param [Hash] opts the optional parameters
  # @return [Dfe]
  describe 'emitir_dce test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for listar_dce
  # Listar DC-e
  # Retorna a lista de DC-e de acordo com os critérios de busca utilizados. As DC-e são retornadas ordenadas pela data da criação, com as mais recentes aparecendo primeiro.
  # @param cpf_cnpj Filtrar pelo CPF ou CNPJ do emitente.    Utilize o valor sem máscara.
  # @param ambiente Identificação do Ambiente.    Valores aceitos: homologacao, producao
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :top Limite no número de objetos a serem retornados pela API, entre 1 e 100.
  # @option opts [Integer] :skip Quantidade de objetos que serão ignorados antes da lista começar a ser retornada.
  # @option opts [Boolean] :inlinecount Inclui no JSON de resposta, na propriedade &#x60;@count&#x60;, o número total de registros que o filtro retornaria, independente dos filtros de paginação.
  # @option opts [String] :referencia Seu identificador único para o documento.
  # @option opts [String] :chave Chave de acesso do DF-e.
  # @option opts [String] :serie Série do DF-e.
  # @return [DfeListagem]
  describe 'listar_dce test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
