=begin
#API Nuvem Fiscal

#API para automação comercial e documentos fiscais.

The version of the OpenAPI document: 2.60.0

Generated by: https://openapi-generator.tech
Generator version: 7.14.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for NuvemFiscalClient::CteSefazMultimodal
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe NuvemFiscalClient::CteSefazMultimodal do
  let(:instance) { NuvemFiscalClient::CteSefazMultimodal.new }

  describe 'test an instance of CteSefazMultimodal' do
    it 'should create an instance of CteSefazMultimodal' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(NuvemFiscalClient::CteSefazMultimodal)
    end
  end

  describe 'test attribute "cotm"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "ind_negociavel"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "seg"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
