=begin
#API Nuvem Fiscal

#API para automação comercial e documentos fiscais.

The version of the OpenAPI document: 2.60.0

Generated by: https://openapi-generator.tech
Generator version: 7.14.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for NuvemFiscalClient::DfeSefazStatus
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe NuvemFiscalClient::DfeSefazStatus do
  let(:instance) { NuvemFiscalClient::DfeSefazStatus.new }

  describe 'test an instance of DfeSefazStatus' do
    it 'should create an instance of DfeSefazStatus' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(NuvemFiscalClient::DfeSefazStatus)
    end
  end

  describe 'test attribute "autorizador"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["AM", "BA", "CE", "GO", "MG", "MS", "MT", "PE", "PR", "RS", "SP", "SVAN", "SVRS", "SVCAN", "SVCRS", "AN", "SVSP", "SVCSP"])
      # validator.allowable_values.each do |value|
      #   expect { instance.autorizador = value }.not_to raise_error
      # end
    end
  end

  describe 'test attribute "ambiente"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["homologacao", "producao"])
      # validator.allowable_values.each do |value|
      #   expect { instance.ambiente = value }.not_to raise_error
      # end
    end
  end

  describe 'test attribute "data_hora_consulta"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "codigo_status"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "motivo_status"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "tempo_medio_resposta"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "data_hora_retorno"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
