=begin
#API Nuvem Fiscal

#API para automação comercial e documentos fiscais.

The version of the OpenAPI document: 2.60.0

Generated by: https://openapi-generator.tech
Generator version: 7.14.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for NuvemFiscalClient::DfeRecibo
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe NuvemFiscalClient::DfeRecibo do
  let(:instance) { NuvemFiscalClient::DfeRecibo.new }

  describe 'test an instance of DfeRecibo' do
    it 'should create an instance of DfeRecibo' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(NuvemFiscalClient::DfeRecibo)
    end
  end

  describe 'test attribute "numero"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "codigo_status"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "motivo_status"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "data_recebimento"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "codigo_mensagem"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "mensagem"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
