=begin
#API Nuvem Fiscal

#API para automação comercial e documentos fiscais.

The version of the OpenAPI document: 2.44.0

Generated by: https://openapi-generator.tech
Generator version: 7.10.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for NuvemfiscalSdkRuby::EmpresaConfigRps
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe NuvemfiscalSdkRuby::EmpresaConfigRps do
  let(:instance) { NuvemfiscalSdkRuby::EmpresaConfigRps.new }

  describe 'test an instance of EmpresaConfigRps' do
    it 'should create an instance of EmpresaConfigRps' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(NuvemfiscalSdkRuby::EmpresaConfigRps)
    end
  end

  describe 'test attribute "lote"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "serie"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "numero"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
