=begin
#API Nuvem Fiscal

#API para automação comercial e documentos fiscais.

The version of the OpenAPI document: 2.44.0

Generated by: https://openapi-generator.tech
Generator version: 7.10.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for NuvemfiscalSdkRuby::MdfeSefazInfUnidCargaVazia
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe NuvemfiscalSdkRuby::MdfeSefazInfUnidCargaVazia do
  let(:instance) { NuvemfiscalSdkRuby::MdfeSefazInfUnidCargaVazia.new }

  describe 'test an instance of MdfeSefazInfUnidCargaVazia' do
    it 'should create an instance of MdfeSefazInfUnidCargaVazia' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(NuvemfiscalSdkRuby::MdfeSefazInfUnidCargaVazia)
    end
  end

  describe 'test attribute "id_unid_carga_vazia"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "tp_unid_carga_vazia"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
