=begin
#API Nuvem Fiscal

#API para automação comercial e documentos fiscais.

The version of the OpenAPI document: 2.60.0

Generated by: https://openapi-generator.tech
Generator version: 7.14.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for NuvemFiscalClient::NfcomSefazGFidelidade
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe NuvemFiscalClient::NfcomSefazGFidelidade do
  let(:instance) { NuvemFiscalClient::NfcomSefazGFidelidade.new }

  describe 'test an instance of NfcomSefazGFidelidade' do
    it 'should create an instance of NfcomSefazGFidelidade' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(NuvemFiscalClient::NfcomSefazGFidelidade)
    end
  end

  describe 'test attribute "qtd_saldo_pts"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "d_ref_saldo_pts"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "qtd_pts_resg"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "d_ref_resg_pts"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
